name: Dockerfile Build

on:
  push:
    branches: [main-1.34]
  pull_request:
    branches: [main-1.34]

jobs:
  build:
    uses: kube-kaptain/buildon-github-actions/.github/workflows/docker-build-dockerfile.yaml@1.0.51
    permissions:
      contents: write
      packages: write
      checks: write
    with:
      tag-version-calculation-strategy: 'file-pattern-match'
      tag-version-pattern-type: 'dockerfile-env-kubectl'
      additional-release-branches: 'main-1.34'
